In [1]:
import torch, torch.onnx, tqdm, time, os, json
import numpy as np
import pandas as pd
import pytorch_lightning as pl
from models.est_model import ResidualRegression, DNNRegression
from torch.utils.data import DataLoader, Dataset, random_split
from pytorch_lightning.callbacks import DeviceStatsMonitor, EarlyStopping
from sklearn.metrics import r2_score

In [2]:
monitor = DeviceStatsMonitor()

In [3]:
# set train setting
save_model = True
train_num_epoch = 50000
min_loss = 100
dl_workers = 0

In [4]:
gpu = torch.device('cuda')
torch.set_float32_matmul_precision('high')

In [5]:
# load hyperparameter of json file
with open('.' + os.sep + os.path.join('models', 'params_dnn_20220207-012403.json'), 'r') as file:
    hyper_params = json.load(file)

n_inputs = hyper_params['n_of_inputs']
n_outputs = hyper_params['n_of_outputs']
n_layers = hyper_params['n_of_layers']

In [6]:
model = DNNRegression(n_inputs, n_layers, n_outputs)
print(model)

DNNRegression(
  (layer_1): Linear(in_features=4, out_features=20, bias=True)
  (layer_2): Linear(in_features=20, out_features=20, bias=True)
  (layer_3): Linear(in_features=20, out_features=6, bias=True)
  (active): ReLU()
  (model): Sequential(
    (0): Linear(in_features=4, out_features=20, bias=True)
    (1): ReLU()
    (2): Linear(in_features=20, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=6, bias=True)
  )
  (loss): MSELoss()
)


In [7]:
data = pd.read_csv('./resources/sim_data.csv')
feature_names = ['lift_weight(ton)', 'lift_height(m)', 'rising_angle(deg)', 'swing_angle(deg)']
target_names = ['left_ground_pressure_min(kg/cm2)', 'left_ground_pressure_max(kg/cm2)', 'left_pressure_length(m)', 'right_ground_pressure_min(kg/cm2)', 'right_ground_pressure_max(kg/cm2)', 'right_pressure_length(m)']

feature_data = []
target_data = []

for feature_name in feature_names:
    feature_data.append(data[feature_name])

for target_name in target_names:
    target_data.append(data[target_name])

feature_data = np.array(feature_data, dtype=np.float32).T
target_data = np.array(target_data, dtype=np.float32).T

class TensorDataset(Dataset):
    def __init__(self, feature, target):
        self.x_data = torch.tensor(feature)
        self.y_data = torch.tensor(target)
        self.len = self.x_data.shape[0]

    def __getitem__(self, index):
        return self.x_data[index], self.y_data[index]

    def __len__(self):
        return self.len

train_dataset = TensorDataset(feature_data, target_data)
train_data_loader = DataLoader(train_dataset, batch_size=len(train_dataset), num_workers=16)

In [8]:
# train model
early_stop_callback = EarlyStopping(monitor='train_loss', mode='min', verbose=True, min_delta=0.001, patience=100)
trainer = pl.Trainer(callbacks=[early_stop_callback], accelerator='cuda', enable_progress_bar=True, max_epochs=10000)

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [9]:
trainer.fit(model=model, train_dataloaders=train_data_loader)

Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
Initializing distributed: GLOBAL_RANK: 1, MEMBER: 2/2
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 2 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]

  | Name    | Type       | Params
---------------------------------------
0 | layer_1 | Linear     | 100   
1 | layer_2 | Linear     | 420   
2 | layer_3 | Linear     | 126   
3 | active  | ReLU       | 0     
4 | model   | Sequential | 646   
5 | loss    | MSELoss    | 0     
---------------------------------------
646       Trainable params
0         Non-trainable params
646       Total params
0.003     Total estimated model params size (MB)
/mnt/workspace/estimate_crawler_crane_ground_pressure/venv/lib/

Epoch 0: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, v_num=85]

[rank: 0] Metric train_loss improved. New best score: 22.328
[rank: 1] Metric train_loss improved. New best score: 20.100


Epoch 1: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, v_num=85]

[rank: 0] Metric train_loss improved by 11.097 >= min_delta = 0.001. New best score: 11.231
[rank: 1] Metric train_loss improved by 9.729 >= min_delta = 0.001. New best score: 10.371


Epoch 2: 100%|██████████| 1/1 [00:00<00:00,  1.42it/s, v_num=85]

[rank: 0] Metric train_loss improved by 5.965 >= min_delta = 0.001. New best score: 5.267
[rank: 1] Metric train_loss improved by 4.838 >= min_delta = 0.001. New best score: 5.532


Epoch 3: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s, v_num=85]

[rank: 0] Metric train_loss improved by 3.122 >= min_delta = 0.001. New best score: 2.145
[rank: 1] Metric train_loss improved by 3.136 >= min_delta = 0.001. New best score: 2.397


Epoch 6: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.094 >= min_delta = 0.001. New best score: 2.051
[rank: 1] Metric train_loss improved by 0.215 >= min_delta = 0.001. New best score: 2.181


Epoch 7: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.520 >= min_delta = 0.001. New best score: 1.530
[rank: 1] Metric train_loss improved by 0.962 >= min_delta = 0.001. New best score: 1.220


Epoch 8: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.034 >= min_delta = 0.001. New best score: 1.496
[rank: 1] Metric train_loss improved by 0.070 >= min_delta = 0.001. New best score: 1.150


Epoch 12: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.122 >= min_delta = 0.001. New best score: 1.374


Epoch 13: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.039 >= min_delta = 0.001. New best score: 1.335


Epoch 14: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.127 >= min_delta = 0.001. New best score: 1.209


Epoch 15: 100%|██████████| 1/1 [00:00<00:00,  1.34it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.131 >= min_delta = 0.001. New best score: 1.078


Epoch 19: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.021 >= min_delta = 0.001. New best score: 1.128


Epoch 20: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.160 >= min_delta = 0.001. New best score: 0.968


Epoch 21: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.225 >= min_delta = 0.001. New best score: 0.853


Epoch 22: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.056 >= min_delta = 0.001. New best score: 0.796


Epoch 23: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.123 >= min_delta = 0.001. New best score: 0.845


Epoch 26: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.061 >= min_delta = 0.001. New best score: 0.785


Epoch 27: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.792


Epoch 28: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.010 >= min_delta = 0.001. New best score: 0.775


Epoch 30: 100%|██████████| 1/1 [00:00<00:00,  1.20it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.125 >= min_delta = 0.001. New best score: 0.666


Epoch 31: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.042 >= min_delta = 0.001. New best score: 0.733


Epoch 35: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.027 >= min_delta = 0.001. New best score: 0.707


Epoch 37: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.103 >= min_delta = 0.001. New best score: 0.604


Epoch 48: 100%|██████████| 1/1 [00:00<00:00,  1.77it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.071 >= min_delta = 0.001. New best score: 0.596


Epoch 51: 100%|██████████| 1/1 [00:00<00:00,  1.72it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.016 >= min_delta = 0.001. New best score: 0.580


Epoch 61: 100%|██████████| 1/1 [00:00<00:00,  1.41it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.025 >= min_delta = 0.001. New best score: 0.555


Epoch 62: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.030 >= min_delta = 0.001. New best score: 0.573


Epoch 63: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.018 >= min_delta = 0.001. New best score: 0.537


Epoch 68: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.009 >= min_delta = 0.001. New best score: 0.565


Epoch 69: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.020 >= min_delta = 0.001. New best score: 0.545


Epoch 76: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.065 >= min_delta = 0.001. New best score: 0.480


Epoch 77: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.024 >= min_delta = 0.001. New best score: 0.457


Epoch 82: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.019 >= min_delta = 0.001. New best score: 0.438


Epoch 89: 100%|██████████| 1/1 [00:01<00:00,  1.01s/it, v_num=85]

[rank: 0] Metric train_loss improved by 0.049 >= min_delta = 0.001. New best score: 0.488


Epoch 95: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.096 >= min_delta = 0.001. New best score: 0.341


Epoch 99: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.025 >= min_delta = 0.001. New best score: 0.463


Epoch 107: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.057 >= min_delta = 0.001. New best score: 0.406


Epoch 109: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.056 >= min_delta = 0.001. New best score: 0.350


Epoch 118: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.014 >= min_delta = 0.001. New best score: 0.328


Epoch 127: 100%|██████████| 1/1 [00:00<00:00,  1.11it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.080 >= min_delta = 0.001. New best score: 0.270


Epoch 131: 100%|██████████| 1/1 [00:00<00:00,  1.14it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.006 >= min_delta = 0.001. New best score: 0.322


Epoch 132: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.320


Epoch 133: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.050 >= min_delta = 0.001. New best score: 0.270


Epoch 136: 100%|██████████| 1/1 [00:00<00:00,  1.14it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.021 >= min_delta = 0.001. New best score: 0.249


Epoch 137: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.086 >= min_delta = 0.001. New best score: 0.185


Epoch 142: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.077 >= min_delta = 0.001. New best score: 0.173


Epoch 143: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.024 >= min_delta = 0.001. New best score: 0.161


Epoch 148: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.006 >= min_delta = 0.001. New best score: 0.166


Epoch 150: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.156


Epoch 151: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.019 >= min_delta = 0.001. New best score: 0.137


Epoch 153: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.014 >= min_delta = 0.001. New best score: 0.153


Epoch 156: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.136


Epoch 157: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.013 >= min_delta = 0.001. New best score: 0.140


Epoch 158: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.016 >= min_delta = 0.001. New best score: 0.124


Epoch 160: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.134


Epoch 161: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.004 >= min_delta = 0.001. New best score: 0.130


Epoch 162: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.014 >= min_delta = 0.001. New best score: 0.116


Epoch 165: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.113


Epoch 167: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.122


Epoch 170: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.012 >= min_delta = 0.001. New best score: 0.109


Epoch 173: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.013 >= min_delta = 0.001. New best score: 0.100


Epoch 180: 100%|██████████| 1/1 [00:00<00:00,  1.40it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.006 >= min_delta = 0.001. New best score: 0.094


Epoch 181: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.107


Epoch 182: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.104


Epoch 184: 100%|██████████| 1/1 [00:00<00:00,  1.33it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.010 >= min_delta = 0.001. New best score: 0.094


Epoch 187: 100%|██████████| 1/1 [00:00<00:00,  1.35it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.092


Epoch 189: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.007 >= min_delta = 0.001. New best score: 0.088


Epoch 191: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.008 >= min_delta = 0.001. New best score: 0.083


Epoch 195: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.006 >= min_delta = 0.001. New best score: 0.082


Epoch 199: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.011 >= min_delta = 0.001. New best score: 0.071


Epoch 200: 100%|██████████| 1/1 [00:01<00:00,  1.03s/it, v_num=85]

[rank: 1] Metric train_loss improved by 0.007 >= min_delta = 0.001. New best score: 0.076


Epoch 202: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.074


Epoch 209: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.066


Epoch 213: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.069


Epoch 216: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.068


Epoch 218: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.004 >= min_delta = 0.001. New best score: 0.062


Epoch 222: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.066


Epoch 223: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.058


Epoch 224: 100%|██████████| 1/1 [00:00<00:00,  1.35it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.063


Epoch 233: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.060


Epoch 239: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.055


Epoch 242: 100%|██████████| 1/1 [00:00<00:00,  1.29it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.004 >= min_delta = 0.001. New best score: 0.053


Epoch 246: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.007 >= min_delta = 0.001. New best score: 0.048


Epoch 252: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.052


Epoch 267: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.003 >= min_delta = 0.001. New best score: 0.049


Epoch 271: 100%|██████████| 1/1 [00:00<00:00,  1.36it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.046


Epoch 274: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.046


Epoch 275: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.044


Epoch 281: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.045


Epoch 299: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.043


Epoch 301: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.006 >= min_delta = 0.001. New best score: 0.039


Epoch 313: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.038


Epoch 316: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.033


Epoch 320: 100%|██████████| 1/1 [00:00<00:00,  1.15it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.037


Epoch 335: 100%|██████████| 1/1 [00:00<00:00,  1.30it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.035


Epoch 343: 100%|██████████| 1/1 [00:00<00:00,  1.31it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.034


Epoch 353: 100%|██████████| 1/1 [00:00<00:00,  1.18it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.032


Epoch 365: 100%|██████████| 1/1 [00:00<00:00,  1.05it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.004 >= min_delta = 0.001. New best score: 0.030


Epoch 374: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.029


Epoch 375: 100%|██████████| 1/1 [00:00<00:00,  1.17it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.031


Epoch 389: 100%|██████████| 1/1 [00:00<00:00,  1.13it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.030


Epoch 413: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.025


Epoch 419: 100%|██████████| 1/1 [00:00<00:00,  1.24it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.028


Epoch 450: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.026


Epoch 467: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.024


Epoch 473: 100%|██████████| 1/1 [00:00<00:00,  1.15it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.024


Epoch 475: 100%|██████████| 1/1 [00:00<00:00,  1.14it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.022


Epoch 502: 100%|██████████| 1/1 [00:00<00:00,  1.32it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.022


Epoch 504: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.021


Epoch 522: 100%|██████████| 1/1 [00:00<00:00,  1.26it/s, v_num=85]

[rank: 1] Metric train_loss improved by 0.002 >= min_delta = 0.001. New best score: 0.018


Epoch 560: 100%|██████████| 1/1 [00:00<00:00,  1.38it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.001 >= min_delta = 0.001. New best score: 0.021


Epoch 610: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s, v_num=85]

[rank: 0] Metric train_loss improved by 0.005 >= min_delta = 0.001. New best score: 0.016


Epoch 622: 100%|██████████| 1/1 [00:00<00:00,  1.39it/s, v_num=85]

[rank: 1] Monitored metric train_loss did not improve in the last 100 records. Best score: 0.018. Signaling Trainer to stop.


Epoch 622: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s, v_num=85]


In [11]:
torch.save(model.state_dict(), './models/est_ground_pressure.pt')

In [10]:
model.eval()
for data in train_dataset:
    print(r2_score(data[1].detach().numpy() ,model(data[0]).detach().numpy()))
    print(model(data[0]).detach().numpy())
    print(data[1].detach().numpy())

0.9871332765655791
[ 3.5765715  -0.01149936  3.5738328   4.2014933  -0.02112616  3.5647104 ]
[3.97 0.   3.72 3.97 0.   3.72]
0.9977751262086295
[ 2.4848082e+00 -1.6549062e-03  3.9801366e+00  4.6294141e+00
 -4.1214563e-03  3.9723408e+00]
[2.61 0.   4.1  4.58 0.   4.1 ]
0.997350976381099
[ 8.8815498e-01 -8.0041401e-04  5.5741425e+00  4.2900510e+00
 -4.9642250e-03  5.5770316e+00]
[1.15 0.   5.59 4.13 0.   5.59]
0.994179251019459
[ 2.6416721  -0.00593635  5.1493454   2.722249   -0.01332249  5.1434326 ]
[2.93 0.   5.04 2.93 0.   5.04]
0.9984016971704133
[2.0802212  0.01571838 5.3427076  3.5589108  0.02363087 5.341245  ]
[2.16 0.   5.34 3.36 0.   5.34]
0.9973668266627363
[0.9861548  0.05872941 6.400102   3.2033217  0.09728083 6.3982706 ]
[1.25 0.   6.53 3.27 0.   6.53]
0.996679899489965
[2.4627676  0.00794786 6.505856   2.0329432  0.00753776 6.512319  ]
[2.21 0.   6.68 2.21 0.   6.68]
0.9994015860874478
[1.675635   0.03309165 6.705278   2.4884076  0.05138322 6.710149  ]
[1.83 0.04 6.75 2.46 

In [12]:
torch.onnx.export(model, torch.zeros(4), './models/est_ground_pressure.onnx')

============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

